{
 "title": "Develocity Savings",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"build-scans\",\n    tag: \"project\",\n    predicate: (r) => r.project != \"all\",\n    start: -30d\n)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Project Count (with cache savings)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"build-scans\",\n    tag: \"project\",\n    predicate: (r) => true,\n    start: -30d\n)\n|> count()\n"
    }
   ]
  },
  {
   "title": "Cache Savings",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cache\")\n  |> filter(fn: (r) => r[\"_field\"] == \"build_cache_savings_ms\")\n  |> mean()\n  |> group(columns: [\"_field\"])\n  |> sum()\n"
    }
   ]
  },
  {
   "title": "Build Time (with cache savings)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cache\")\n  |> filter(fn: (r) => r[\"_field\"] == \"build_duration_ms\")\n  |> mean()\n  |> group(columns: [\"_field\"])\n  |> sum()\n"
    }
   ]
  },
  {
   "title": "Build Count (with cache savings)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cache\")\n  |> filter(fn: (r) => r[\"_field\"] == \"build_count\")\n  |> mean()  \n  |> group(columns: [\"_field\"])\n  |> sum()\n\n"
    }
   ]
  },
  {
   "title": "Project Count with cache savings > 10%",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"cache\")\n    |> filter(fn: (r) => r[\"_field\"] == \"serial_clock_savings_rate\")\n    |> filter(fn: (r) => r[\"_value\"] >= 10)\n    |> mean()\n    |> group(columns: [\"_field\"])\n    |> count()\n"
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Build count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cache\" and\n    r._field == \"build_count\" and\n    (contains(value: r.project, set: ${project:json}) or contains(value: \"all\", set: ${project:json}))\n  )\n  |> drop(columns: [\"avoidanceOutcome\", \"taskType\", \"taskName\", \"buildScanId\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"build_count\")"
    }
   ]
  },
  {
   "title": "Build Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cache\" and\n    r._field == \"build_duration_ms\" and\n    (contains(value: r.project, set: ${project:json}) or contains(value: \"all\", set: ${project:json}))\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"build_count\")"
    }
   ]
  },
  {
   "title": "Build Cache Savings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cache\" and\n    r._field == \"build_cache_savings_ms\" and\n    (contains(value: r.project, set: ${project:json}) or contains(value: \"all\", set: ${project:json}))\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"build_count\")"
    }
   ]
  }
 ]
}